/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "surface": "#fbf8ff",
        "outline": "#8f6f71",
        "on-error-container": "#93000a",
        "tertiary-container": "#00855b",
        "surface-bright": "#fbf8ff",
        "on-secondary-container": "#730425",
        "surface-container-highest": "#e3e1ec",
        "surface-container-low": "#f4f2fd",
        "secondary-fixed": "#ffdadc",
        "primary-fixed": "#ffdadb",
        "surface-variant": "#e3e1ec",
        "on-tertiary": "#ffffff",
        "primary-container": "#dc2c4f",
        "secondary": "#a93349",
        "inverse-primary": "#ffb2b7",
        "on-surface": "#1a1b22",
        "primary-fixed-dim": "#ffb2b7",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed": "#40000d",
        "on-secondary": "#ffffff",
        "background": "#fbf8ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#fe7488",
        "surface-tint": "#bc0b3b",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary-container": "#f5fff6",
        "on-background": "#1a1b22",
        "error": "#ba1a1a",
        "primary": "#b90538",
        "on-secondary-fixed": "#400010",
        "inverse-on-surface": "#f1effa",
        "surface-container": "#eeedf7",
        "surface-container-high": "#e8e7f1",
        "on-primary-fixed-variant": "#92002a",
        "surface-dim": "#dad9e3",
        "tertiary": "#006947",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#891933",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#ffb2b9",
        "outline-variant": "#e3bdbf",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#2f3038",
        "on-surface-variant": "#5b4041"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "margin": "1rem"
      },
      fontFamily: {
        "sans": ["Inter", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "metric-display": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "metric-display": ["32px", { lineHeight: "36px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }]
      },
      boxShadow: {
        'glow-primary': '0 10px 25px -4px rgba(244, 63, 94, 0.25), 0 4px 10px -2px rgba(244, 63, 94, 0.15)',
        'card-warm': '0 4px 20px -2px rgba(244, 63, 94, 0.06), 0 2px 6px -1px rgba(0, 0, 0, 0.02)',
        'nav-warm': '0 -8px 24px -4px rgba(244, 63, 94, 0.08)'
      }
    }
  },
  plugins: [],
}
